// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package test

import (
	fmt "fmt"
	_ "github.com/TheThingsIndustries/protoc-gen-go-flags/annotations"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NonSemantic struct {
	Semantic             *NonSemantic_Semantic `protobuf:"bytes,1,opt,name=semantic,proto3" json:"semantic,omitempty"`
	OverruledSemantic    *NonSemantic_Semantic `protobuf:"bytes,2,opt,name=overruled_semantic,json=overruledSemantic,proto3" json:"overruled_semantic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NonSemantic) Reset()         { *m = NonSemantic{} }
func (m *NonSemantic) String() string { return proto.CompactTextString(m) }
func (*NonSemantic) ProtoMessage()    {}
func (*NonSemantic) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}
func (m *NonSemantic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonSemantic.Unmarshal(m, b)
}
func (m *NonSemantic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonSemantic.Marshal(b, m, deterministic)
}
func (m *NonSemantic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonSemantic.Merge(m, src)
}
func (m *NonSemantic) XXX_Size() int {
	return xxx_messageInfo_NonSemantic.Size(m)
}
func (m *NonSemantic) XXX_DiscardUnknown() {
	xxx_messageInfo_NonSemantic.DiscardUnknown(m)
}

var xxx_messageInfo_NonSemantic proto.InternalMessageInfo

func (m *NonSemantic) GetSemantic() *NonSemantic_Semantic {
	if m != nil {
		return m.Semantic
	}
	return nil
}

func (m *NonSemantic) GetOverruledSemantic() *NonSemantic_Semantic {
	if m != nil {
		return m.OverruledSemantic
	}
	return nil
}

type NonSemantic_Semantic struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonSemantic_Semantic) Reset()         { *m = NonSemantic_Semantic{} }
func (m *NonSemantic_Semantic) String() string { return proto.CompactTextString(m) }
func (*NonSemantic_Semantic) ProtoMessage()    {}
func (*NonSemantic_Semantic) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}
func (m *NonSemantic_Semantic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonSemantic_Semantic.Unmarshal(m, b)
}
func (m *NonSemantic_Semantic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonSemantic_Semantic.Marshal(b, m, deterministic)
}
func (m *NonSemantic_Semantic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonSemantic_Semantic.Merge(m, src)
}
func (m *NonSemantic_Semantic) XXX_Size() int {
	return xxx_messageInfo_NonSemantic_Semantic.Size(m)
}
func (m *NonSemantic_Semantic) XXX_DiscardUnknown() {
	xxx_messageInfo_NonSemantic_Semantic.DiscardUnknown(m)
}

var xxx_messageInfo_NonSemantic_Semantic proto.InternalMessageInfo

func init() {
	proto.RegisterType((*NonSemantic)(nil), "thethings.flags.test.NonSemantic")
	proto.RegisterType((*NonSemantic_Semantic)(nil), "thethings.flags.test.NonSemantic.Semantic")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x14, 0x45, 0xdb, 0x41, 0x4a, 0xc8, 0x20, 0x38, 0xc5, 0x85, 0x2d, 0x08, 0x83, 0x2b, 0x11, 0x9a,
	0x8a, 0x2e, 0x44, 0x97, 0xb3, 0x73, 0x33, 0x8b, 0x71, 0x56, 0x6e, 0x24, 0xd3, 0x79, 0xa6, 0x81,
	0xf6, 0x3d, 0x49, 0x5e, 0xfd, 0xa8, 0x7e, 0x92, 0x9f, 0xd1, 0x2f, 0x10, 0x33, 0xb6, 0xb8, 0x70,
	0x33, 0xbb, 0x43, 0x6e, 0x72, 0xee, 0x25, 0xf2, 0xb4, 0x05, 0xef, 0xb5, 0x01, 0xf5, 0xe1, 0x88,
	0x29, 0x3d, 0xe7, 0x1a, 0xb8, 0xb6, 0x68, 0xbc, 0x7a, 0x6f, 0xb4, 0xf1, 0x8a, 0xc1, 0x73, 0xbe,
	0xd0, 0x88, 0xc4, 0x9a, 0x2d, 0xa1, 0x3f, 0x5c, 0xcc, 0x2f, 0x2d, 0x32, 0x38, 0xd4, 0x4d, 0x69,
	0xc8, 0x50, 0x38, 0x0b, 0x74, 0x88, 0xaf, 0xbe, 0x62, 0x39, 0x5f, 0x13, 0xbe, 0x40, 0xab, 0x91,
	0x6d, 0x95, 0xae, 0xa5, 0xf0, 0xbf, 0x7c, 0x11, 0x2f, 0xe3, 0xeb, 0xf9, 0xdd, 0x8d, 0xfa, 0xaf,
	0x4a, 0xfd, 0x79, 0xa4, 0x46, 0x58, 0x25, 0x43, 0x9f, 0xcd, 0x44, 0xb4, 0x99, 0x1c, 0x69, 0x25,
	0x53, 0xfa, 0x04, 0xe7, 0xba, 0x06, 0xf6, 0x6f, 0x93, 0x79, 0x76, 0xb4, 0x59, 0x0c, 0x7d, 0x76,
	0x22, 0xa2, 0xdb, 0x68, 0xb3, 0x98, 0x7c, 0x63, 0x98, 0x4b, 0x29, 0x46, 0x7e, 0x92, 0x43, 0x9f,
	0x25, 0x22, 0x3a, 0x8b, 0x97, 0xf1, 0xea, 0xf1, 0xf5, 0xc1, 0x58, 0xae, 0xbb, 0x9d, 0xaa, 0xa8,
	0x2d, 0xb7, 0x35, 0x6c, 0x43, 0xd9, 0x33, 0xee, 0x3b, 0xcf, 0xce, 0x82, 0x2f, 0xc3, 0x27, 0x54,
	0x85, 0x01, 0x2c, 0x0c, 0x15, 0x61, 0x44, 0xf9, 0x33, 0x62, 0x97, 0x84, 0xe4, 0xfe, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0xda, 0x81, 0x33, 0x67, 0x77, 0x01, 0x00, 0x00,
}
