// Code generated by protoc-gen-go-flags. DO NOT EDIT.
// versions:
// - protoc-gen-go-flags v0.0.0-dev
// - protoc              v3.9.1
// source: message.proto

package test

import (
	flagsplugin "github.com/TheThingsIndustries/protoc-gen-go-flags/flagsplugin"
	pflag "github.com/spf13/pflag"
)

// AddSetFlagsForNonSemantic adds flags to select fields in NonSemantic.
func AddSetFlagsForNonSemantic(flags *pflag.FlagSet, prefix string, hidden bool) {
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("semantic", prefix), "", flagsplugin.WithHidden(hidden)))
	// FIXME: Skipping OverruledSemantic because it does not seem to implement AddSetFlags.
}

// SetFromFlags sets the NonSemantic message from flags.
func (m *NonSemantic) SetFromFlags(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	if _, changed, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("semantic", prefix)); err != nil {
		return nil, err
	} else if changed {
		m.Semantic = &NonSemantic_Semantic{}
		paths = append(paths, flagsplugin.Prefix("semantic", prefix))
	}
	// FIXME: Skipping OverruledSemantic because it does not seem to implement AddSetFlags.
	return paths, nil
}

// AddSetFlagsForOneOf adds flags to select fields in OneOf.
func AddSetFlagsForOneOf(flags *pflag.FlagSet, prefix string, hidden bool) {
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("option.semantic", prefix), "", flagsplugin.WithHidden(hidden)))
	flags.AddFlag(flagsplugin.NewBoolFlag(flagsplugin.Prefix("option.non-semantic", prefix), "", flagsplugin.WithHidden(hidden)))
}

// SetFromFlags sets the OneOf message from flags.
func (m *OneOf) SetFromFlags(flags *pflag.FlagSet, prefix string) (paths []string, err error) {
	if _, changed, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("option.semantic", prefix)); err != nil {
		return nil, err
	} else if changed {
		ov := &OneOf_Semantic_{}
		paths = append(paths, flagsplugin.Prefix("option.semantic", prefix))
		m.Option = ov
	}
	if _, changed, err := flagsplugin.GetBool(flags, flagsplugin.Prefix("option.non_semantic", prefix)); err != nil {
		return nil, err
	} else if changed {
		ov := &OneOf_NonSemantic_{}
		paths = append(paths, flagsplugin.Prefix("option.non_semantic", prefix))
		m.Option = ov
	}
	return paths, nil
}
