// Copyright © 2021 The Things Industries B.V.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: message.proto

package test

import (
	_ "github.com/TheThingsIndustries/protoc-gen-go-flags/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SemanticalMessage struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	Empty          *SemanticalMessage_Empty    `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	EmptyOverruled *SemanticalMessage_Empty    `protobuf:"bytes,2,opt,name=empty_overruled,json=emptyOverruled,proto3" json:"empty_overruled,omitempty"`
	NonEmpty       *SemanticalMessage_NonEmpty `protobuf:"bytes,3,opt,name=non_empty,json=nonEmpty,proto3" json:"non_empty,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SemanticalMessage) Reset() {
	*x = SemanticalMessage{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticalMessage) ProtoMessage() {}

func (x *SemanticalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticalMessage.ProtoReflect.Descriptor instead.
func (*SemanticalMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *SemanticalMessage) GetEmpty() *SemanticalMessage_Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

func (x *SemanticalMessage) GetEmptyOverruled() *SemanticalMessage_Empty {
	if x != nil {
		return x.EmptyOverruled
	}
	return nil
}

func (x *SemanticalMessage) GetNonEmpty() *SemanticalMessage_NonEmpty {
	if x != nil {
		return x.NonEmpty
	}
	return nil
}

type SemanticalOneOfMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Option:
	//
	//	*SemanticalOneOfMessage_Semantical
	//	*SemanticalOneOfMessage_Alternative
	Option        isSemanticalOneOfMessage_Option `protobuf_oneof:"option"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticalOneOfMessage) Reset() {
	*x = SemanticalOneOfMessage{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticalOneOfMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticalOneOfMessage) ProtoMessage() {}

func (x *SemanticalOneOfMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticalOneOfMessage.ProtoReflect.Descriptor instead.
func (*SemanticalOneOfMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *SemanticalOneOfMessage) GetOption() isSemanticalOneOfMessage_Option {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *SemanticalOneOfMessage) GetSemantical() *SemanticalOneOfMessage_Empty {
	if x != nil {
		if x, ok := x.Option.(*SemanticalOneOfMessage_Semantical); ok {
			return x.Semantical
		}
	}
	return nil
}

func (x *SemanticalOneOfMessage) GetAlternative() *SemanticalOneOfMessage_NonEmpty {
	if x != nil {
		if x, ok := x.Option.(*SemanticalOneOfMessage_Alternative); ok {
			return x.Alternative
		}
	}
	return nil
}

type isSemanticalOneOfMessage_Option interface {
	isSemanticalOneOfMessage_Option()
}

type SemanticalOneOfMessage_Semantical struct {
	Semantical *SemanticalOneOfMessage_Empty `protobuf:"bytes,1,opt,name=semantical,proto3,oneof"`
}

type SemanticalOneOfMessage_Alternative struct {
	Alternative *SemanticalOneOfMessage_NonEmpty `protobuf:"bytes,2,opt,name=alternative,proto3,oneof"`
}

func (*SemanticalOneOfMessage_Semantical) isSemanticalOneOfMessage_Option() {}

func (*SemanticalOneOfMessage_Alternative) isSemanticalOneOfMessage_Option() {}

type SemanticalMessage_Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticalMessage_Empty) Reset() {
	*x = SemanticalMessage_Empty{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticalMessage_Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticalMessage_Empty) ProtoMessage() {}

func (x *SemanticalMessage_Empty) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticalMessage_Empty.ProtoReflect.Descriptor instead.
func (*SemanticalMessage_Empty) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 0}
}

type SemanticalMessage_NonEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoolValue     bool                   `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticalMessage_NonEmpty) Reset() {
	*x = SemanticalMessage_NonEmpty{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticalMessage_NonEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticalMessage_NonEmpty) ProtoMessage() {}

func (x *SemanticalMessage_NonEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticalMessage_NonEmpty.ProtoReflect.Descriptor instead.
func (*SemanticalMessage_NonEmpty) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SemanticalMessage_NonEmpty) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

type SemanticalOneOfMessage_Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticalOneOfMessage_Empty) Reset() {
	*x = SemanticalOneOfMessage_Empty{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticalOneOfMessage_Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticalOneOfMessage_Empty) ProtoMessage() {}

func (x *SemanticalOneOfMessage_Empty) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticalOneOfMessage_Empty.ProtoReflect.Descriptor instead.
func (*SemanticalOneOfMessage_Empty) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1, 0}
}

type SemanticalOneOfMessage_NonEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoolValue     bool                   `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticalOneOfMessage_NonEmpty) Reset() {
	*x = SemanticalOneOfMessage_NonEmpty{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticalOneOfMessage_NonEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticalOneOfMessage_NonEmpty) ProtoMessage() {}

func (x *SemanticalOneOfMessage_NonEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticalOneOfMessage_NonEmpty.ProtoReflect.Descriptor instead.
func (*SemanticalOneOfMessage_NonEmpty) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1, 1}
}

func (x *SemanticalOneOfMessage_NonEmpty) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x14thethings.flags.test\x1a!thethings/flags/annotations.proto\"\xdb\x02\n" +
	"\x11SemanticalMessage\x12C\n" +
	"\x05empty\x18\x01 \x01(\v2-.thethings.flags.test.SemanticalMessage.EmptyR\x05empty\x12^\n" +
	"\x0fempty_overruled\x18\x02 \x01(\v2-.thethings.flags.test.SemanticalMessage.EmptyB\x06\xf2\xaa\x19\x020\x00R\x0eemptyOverruled\x12M\n" +
	"\tnon_empty\x18\x03 \x01(\v20.thethings.flags.test.SemanticalMessage.NonEmptyR\bnonEmpty\x1a\x11\n" +
	"\x05Empty:\b\xf2\xaa\x19\x04\b\x00\x10\x01\x1a3\n" +
	"\bNonEmpty\x12\x1d\n" +
	"\n" +
	"bool_value\x18\x01 \x01(\bR\tboolValue:\b\xf2\xaa\x19\x04\b\x00\x10\x01:\n" +
	"\xf2\xaa\x19\x06\b\x00\x10\x01 \x01\"\x9d\x02\n" +
	"\x16SemanticalOneOfMessage\x12T\n" +
	"\n" +
	"semantical\x18\x01 \x01(\v22.thethings.flags.test.SemanticalOneOfMessage.EmptyH\x00R\n" +
	"semantical\x12Y\n" +
	"\valternative\x18\x02 \x01(\v25.thethings.flags.test.SemanticalOneOfMessage.NonEmptyH\x00R\valternative\x1a\a\n" +
	"\x05Empty\x1a3\n" +
	"\bNonEmpty\x12\x1d\n" +
	"\n" +
	"bool_value\x18\x01 \x01(\bR\tboolValue:\b\xf2\xaa\x19\x04\b\x00\x10\x01:\n" +
	"\xf2\xaa\x19\x06\b\x00\x10\x01 \x01B\b\n" +
	"\x06optionB9Z7github.com/TheThingsIndustries/protoc-gen-go-flags/testb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_message_proto_goTypes = []any{
	(*SemanticalMessage)(nil),               // 0: thethings.flags.test.SemanticalMessage
	(*SemanticalOneOfMessage)(nil),          // 1: thethings.flags.test.SemanticalOneOfMessage
	(*SemanticalMessage_Empty)(nil),         // 2: thethings.flags.test.SemanticalMessage.Empty
	(*SemanticalMessage_NonEmpty)(nil),      // 3: thethings.flags.test.SemanticalMessage.NonEmpty
	(*SemanticalOneOfMessage_Empty)(nil),    // 4: thethings.flags.test.SemanticalOneOfMessage.Empty
	(*SemanticalOneOfMessage_NonEmpty)(nil), // 5: thethings.flags.test.SemanticalOneOfMessage.NonEmpty
}
var file_message_proto_depIdxs = []int32{
	2, // 0: thethings.flags.test.SemanticalMessage.empty:type_name -> thethings.flags.test.SemanticalMessage.Empty
	2, // 1: thethings.flags.test.SemanticalMessage.empty_overruled:type_name -> thethings.flags.test.SemanticalMessage.Empty
	3, // 2: thethings.flags.test.SemanticalMessage.non_empty:type_name -> thethings.flags.test.SemanticalMessage.NonEmpty
	4, // 3: thethings.flags.test.SemanticalOneOfMessage.semantical:type_name -> thethings.flags.test.SemanticalOneOfMessage.Empty
	5, // 4: thethings.flags.test.SemanticalOneOfMessage.alternative:type_name -> thethings.flags.test.SemanticalOneOfMessage.NonEmpty
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[1].OneofWrappers = []any{
		(*SemanticalOneOfMessage_Semantical)(nil),
		(*SemanticalOneOfMessage_Alternative)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
