// Copyright © 2021 The Things Industries B.V.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wkts.proto

package test

import (
	_ "github.com/TheThingsIndustries/protoc-gen-go-flags/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageWithWKTs struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	DoubleValue     *wrapperspb.DoubleValue   `protobuf:"bytes,1,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	DoubleValues    []*wrapperspb.DoubleValue `protobuf:"bytes,2,rep,name=double_values,json=doubleValues,proto3" json:"double_values,omitempty"`
	FloatValue      *wrapperspb.FloatValue    `protobuf:"bytes,3,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	FloatValues     []*wrapperspb.FloatValue  `protobuf:"bytes,4,rep,name=float_values,json=floatValues,proto3" json:"float_values,omitempty"`
	Int32Value      *wrapperspb.Int32Value    `protobuf:"bytes,5,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Int32Values     []*wrapperspb.Int32Value  `protobuf:"bytes,6,rep,name=int32_values,json=int32Values,proto3" json:"int32_values,omitempty"`
	Int64Value      *wrapperspb.Int64Value    `protobuf:"bytes,7,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Int64Values     []*wrapperspb.Int64Value  `protobuf:"bytes,8,rep,name=int64_values,json=int64Values,proto3" json:"int64_values,omitempty"`
	Uint32Value     *wrapperspb.UInt32Value   `protobuf:"bytes,9,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	Uint32Values    []*wrapperspb.UInt32Value `protobuf:"bytes,10,rep,name=uint32_values,json=uint32Values,proto3" json:"uint32_values,omitempty"`
	Uint64Value     *wrapperspb.UInt64Value   `protobuf:"bytes,11,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Uint64Values    []*wrapperspb.UInt64Value `protobuf:"bytes,12,rep,name=uint64_values,json=uint64Values,proto3" json:"uint64_values,omitempty"`
	BoolValue       *wrapperspb.BoolValue     `protobuf:"bytes,13,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	BoolValues      []*wrapperspb.BoolValue   `protobuf:"bytes,14,rep,name=bool_values,json=boolValues,proto3" json:"bool_values,omitempty"`
	StringValue     *wrapperspb.StringValue   `protobuf:"bytes,15,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	StringValues    []*wrapperspb.StringValue `protobuf:"bytes,16,rep,name=string_values,json=stringValues,proto3" json:"string_values,omitempty"`
	BytesValue      *wrapperspb.BytesValue    `protobuf:"bytes,17,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	BytesValues     []*wrapperspb.BytesValue  `protobuf:"bytes,18,rep,name=bytes_values,json=bytesValues,proto3" json:"bytes_values,omitempty"`
	EmptyValue      *emptypb.Empty            `protobuf:"bytes,19,opt,name=empty_value,json=emptyValue,proto3" json:"empty_value,omitempty"`
	EmptyValues     []*emptypb.Empty          `protobuf:"bytes,20,rep,name=empty_values,json=emptyValues,proto3" json:"empty_values,omitempty"`
	TimestampValue  *timestamppb.Timestamp    `protobuf:"bytes,21,opt,name=timestamp_value,json=timestampValue,proto3" json:"timestamp_value,omitempty"`
	TimestampValues []*timestamppb.Timestamp  `protobuf:"bytes,22,rep,name=timestamp_values,json=timestampValues,proto3" json:"timestamp_values,omitempty"`
	DurationValue   *durationpb.Duration      `protobuf:"bytes,23,opt,name=duration_value,json=durationValue,proto3" json:"duration_value,omitempty"`
	DurationValues  []*durationpb.Duration    `protobuf:"bytes,24,rep,name=duration_values,json=durationValues,proto3" json:"duration_values,omitempty"`
	FieldMaskValue  *fieldmaskpb.FieldMask    `protobuf:"bytes,25,opt,name=field_mask_value,json=fieldMaskValue,proto3" json:"field_mask_value,omitempty"`
	FieldMaskValues []*fieldmaskpb.FieldMask  `protobuf:"bytes,26,rep,name=field_mask_values,json=fieldMaskValues,proto3" json:"field_mask_values,omitempty"`
	ValueValue      *structpb.Value           `protobuf:"bytes,27,opt,name=value_value,json=valueValue,proto3" json:"value_value,omitempty"`
	ValueValues     []*structpb.Value         `protobuf:"bytes,28,rep,name=value_values,json=valueValues,proto3" json:"value_values,omitempty"`
	ListValueValue  *structpb.ListValue       `protobuf:"bytes,29,opt,name=list_value_value,json=listValueValue,proto3" json:"list_value_value,omitempty"`
	ListValueValues []*structpb.ListValue     `protobuf:"bytes,30,rep,name=list_value_values,json=listValueValues,proto3" json:"list_value_values,omitempty"`
	StructValue     *structpb.Struct          `protobuf:"bytes,31,opt,name=struct_value,json=structValue,proto3" json:"struct_value,omitempty"`
	StructValues    []*structpb.Struct        `protobuf:"bytes,32,rep,name=struct_values,json=structValues,proto3" json:"struct_values,omitempty"`
	AnyValue        *anypb.Any                `protobuf:"bytes,33,opt,name=any_value,json=anyValue,proto3" json:"any_value,omitempty"`
	AnyValues       []*anypb.Any              `protobuf:"bytes,34,rep,name=any_values,json=anyValues,proto3" json:"any_values,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageWithWKTs) Reset() {
	*x = MessageWithWKTs{}
	mi := &file_wkts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithWKTs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithWKTs) ProtoMessage() {}

func (x *MessageWithWKTs) ProtoReflect() protoreflect.Message {
	mi := &file_wkts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithWKTs.ProtoReflect.Descriptor instead.
func (*MessageWithWKTs) Descriptor() ([]byte, []int) {
	return file_wkts_proto_rawDescGZIP(), []int{0}
}

func (x *MessageWithWKTs) GetDoubleValue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.DoubleValue
	}
	return nil
}

func (x *MessageWithWKTs) GetDoubleValues() []*wrapperspb.DoubleValue {
	if x != nil {
		return x.DoubleValues
	}
	return nil
}

func (x *MessageWithWKTs) GetFloatValue() *wrapperspb.FloatValue {
	if x != nil {
		return x.FloatValue
	}
	return nil
}

func (x *MessageWithWKTs) GetFloatValues() []*wrapperspb.FloatValue {
	if x != nil {
		return x.FloatValues
	}
	return nil
}

func (x *MessageWithWKTs) GetInt32Value() *wrapperspb.Int32Value {
	if x != nil {
		return x.Int32Value
	}
	return nil
}

func (x *MessageWithWKTs) GetInt32Values() []*wrapperspb.Int32Value {
	if x != nil {
		return x.Int32Values
	}
	return nil
}

func (x *MessageWithWKTs) GetInt64Value() *wrapperspb.Int64Value {
	if x != nil {
		return x.Int64Value
	}
	return nil
}

func (x *MessageWithWKTs) GetInt64Values() []*wrapperspb.Int64Value {
	if x != nil {
		return x.Int64Values
	}
	return nil
}

func (x *MessageWithWKTs) GetUint32Value() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Uint32Value
	}
	return nil
}

func (x *MessageWithWKTs) GetUint32Values() []*wrapperspb.UInt32Value {
	if x != nil {
		return x.Uint32Values
	}
	return nil
}

func (x *MessageWithWKTs) GetUint64Value() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Uint64Value
	}
	return nil
}

func (x *MessageWithWKTs) GetUint64Values() []*wrapperspb.UInt64Value {
	if x != nil {
		return x.Uint64Values
	}
	return nil
}

func (x *MessageWithWKTs) GetBoolValue() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolValue
	}
	return nil
}

func (x *MessageWithWKTs) GetBoolValues() []*wrapperspb.BoolValue {
	if x != nil {
		return x.BoolValues
	}
	return nil
}

func (x *MessageWithWKTs) GetStringValue() *wrapperspb.StringValue {
	if x != nil {
		return x.StringValue
	}
	return nil
}

func (x *MessageWithWKTs) GetStringValues() []*wrapperspb.StringValue {
	if x != nil {
		return x.StringValues
	}
	return nil
}

func (x *MessageWithWKTs) GetBytesValue() *wrapperspb.BytesValue {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *MessageWithWKTs) GetBytesValues() []*wrapperspb.BytesValue {
	if x != nil {
		return x.BytesValues
	}
	return nil
}

func (x *MessageWithWKTs) GetEmptyValue() *emptypb.Empty {
	if x != nil {
		return x.EmptyValue
	}
	return nil
}

func (x *MessageWithWKTs) GetEmptyValues() []*emptypb.Empty {
	if x != nil {
		return x.EmptyValues
	}
	return nil
}

func (x *MessageWithWKTs) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampValue
	}
	return nil
}

func (x *MessageWithWKTs) GetTimestampValues() []*timestamppb.Timestamp {
	if x != nil {
		return x.TimestampValues
	}
	return nil
}

func (x *MessageWithWKTs) GetDurationValue() *durationpb.Duration {
	if x != nil {
		return x.DurationValue
	}
	return nil
}

func (x *MessageWithWKTs) GetDurationValues() []*durationpb.Duration {
	if x != nil {
		return x.DurationValues
	}
	return nil
}

func (x *MessageWithWKTs) GetFieldMaskValue() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMaskValue
	}
	return nil
}

func (x *MessageWithWKTs) GetFieldMaskValues() []*fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMaskValues
	}
	return nil
}

func (x *MessageWithWKTs) GetValueValue() *structpb.Value {
	if x != nil {
		return x.ValueValue
	}
	return nil
}

func (x *MessageWithWKTs) GetValueValues() []*structpb.Value {
	if x != nil {
		return x.ValueValues
	}
	return nil
}

func (x *MessageWithWKTs) GetListValueValue() *structpb.ListValue {
	if x != nil {
		return x.ListValueValue
	}
	return nil
}

func (x *MessageWithWKTs) GetListValueValues() []*structpb.ListValue {
	if x != nil {
		return x.ListValueValues
	}
	return nil
}

func (x *MessageWithWKTs) GetStructValue() *structpb.Struct {
	if x != nil {
		return x.StructValue
	}
	return nil
}

func (x *MessageWithWKTs) GetStructValues() []*structpb.Struct {
	if x != nil {
		return x.StructValues
	}
	return nil
}

func (x *MessageWithWKTs) GetAnyValue() *anypb.Any {
	if x != nil {
		return x.AnyValue
	}
	return nil
}

func (x *MessageWithWKTs) GetAnyValues() []*anypb.Any {
	if x != nil {
		return x.AnyValues
	}
	return nil
}

type MessageWithOneofWKTs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*MessageWithOneofWKTs_DoubleValue
	//	*MessageWithOneofWKTs_FloatValue
	//	*MessageWithOneofWKTs_Int32Value
	//	*MessageWithOneofWKTs_Int64Value
	//	*MessageWithOneofWKTs_Uint32Value
	//	*MessageWithOneofWKTs_Uint64Value
	//	*MessageWithOneofWKTs_BoolValue
	//	*MessageWithOneofWKTs_StringValue
	//	*MessageWithOneofWKTs_BytesValue
	//	*MessageWithOneofWKTs_EmptyValue
	//	*MessageWithOneofWKTs_TimestampValue
	//	*MessageWithOneofWKTs_DurationValue
	//	*MessageWithOneofWKTs_FieldMaskValue
	//	*MessageWithOneofWKTs_ValueValue
	//	*MessageWithOneofWKTs_ListValueValue
	//	*MessageWithOneofWKTs_StructValue
	//	*MessageWithOneofWKTs_AnyValue
	Value         isMessageWithOneofWKTs_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithOneofWKTs) Reset() {
	*x = MessageWithOneofWKTs{}
	mi := &file_wkts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithOneofWKTs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithOneofWKTs) ProtoMessage() {}

func (x *MessageWithOneofWKTs) ProtoReflect() protoreflect.Message {
	mi := &file_wkts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithOneofWKTs.ProtoReflect.Descriptor instead.
func (*MessageWithOneofWKTs) Descriptor() ([]byte, []int) {
	return file_wkts_proto_rawDescGZIP(), []int{1}
}

func (x *MessageWithOneofWKTs) GetValue() isMessageWithOneofWKTs_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetDoubleValue() *wrapperspb.DoubleValue {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetFloatValue() *wrapperspb.FloatValue {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_FloatValue); ok {
			return x.FloatValue
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetInt32Value() *wrapperspb.Int32Value {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_Int32Value); ok {
			return x.Int32Value
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetInt64Value() *wrapperspb.Int64Value {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_Int64Value); ok {
			return x.Int64Value
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetUint32Value() *wrapperspb.UInt32Value {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_Uint32Value); ok {
			return x.Uint32Value
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetUint64Value() *wrapperspb.UInt64Value {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_Uint64Value); ok {
			return x.Uint64Value
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetBoolValue() *wrapperspb.BoolValue {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_BoolValue); ok {
			return x.BoolValue
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetStringValue() *wrapperspb.StringValue {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_StringValue); ok {
			return x.StringValue
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetBytesValue() *wrapperspb.BytesValue {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetEmptyValue() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_EmptyValue); ok {
			return x.EmptyValue
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetDurationValue() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_DurationValue); ok {
			return x.DurationValue
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetFieldMaskValue() *fieldmaskpb.FieldMask {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_FieldMaskValue); ok {
			return x.FieldMaskValue
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetValueValue() *structpb.Value {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_ValueValue); ok {
			return x.ValueValue
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetListValueValue() *structpb.ListValue {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_ListValueValue); ok {
			return x.ListValueValue
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetStructValue() *structpb.Struct {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

func (x *MessageWithOneofWKTs) GetAnyValue() *anypb.Any {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofWKTs_AnyValue); ok {
			return x.AnyValue
		}
	}
	return nil
}

type isMessageWithOneofWKTs_Value interface {
	isMessageWithOneofWKTs_Value()
}

type MessageWithOneofWKTs_DoubleValue struct {
	DoubleValue *wrapperspb.DoubleValue `protobuf:"bytes,1,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type MessageWithOneofWKTs_FloatValue struct {
	FloatValue *wrapperspb.FloatValue `protobuf:"bytes,2,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type MessageWithOneofWKTs_Int32Value struct {
	Int32Value *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type MessageWithOneofWKTs_Int64Value struct {
	Int64Value *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type MessageWithOneofWKTs_Uint32Value struct {
	Uint32Value *wrapperspb.UInt32Value `protobuf:"bytes,5,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type MessageWithOneofWKTs_Uint64Value struct {
	Uint64Value *wrapperspb.UInt64Value `protobuf:"bytes,6,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type MessageWithOneofWKTs_BoolValue struct {
	BoolValue *wrapperspb.BoolValue `protobuf:"bytes,7,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type MessageWithOneofWKTs_StringValue struct {
	StringValue *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type MessageWithOneofWKTs_BytesValue struct {
	BytesValue *wrapperspb.BytesValue `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type MessageWithOneofWKTs_EmptyValue struct {
	EmptyValue *emptypb.Empty `protobuf:"bytes,10,opt,name=empty_value,json=emptyValue,proto3,oneof"`
}

type MessageWithOneofWKTs_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type MessageWithOneofWKTs_DurationValue struct {
	DurationValue *durationpb.Duration `protobuf:"bytes,12,opt,name=duration_value,json=durationValue,proto3,oneof"`
}

type MessageWithOneofWKTs_FieldMaskValue struct {
	FieldMaskValue *fieldmaskpb.FieldMask `protobuf:"bytes,13,opt,name=field_mask_value,json=fieldMaskValue,proto3,oneof"`
}

type MessageWithOneofWKTs_ValueValue struct {
	ValueValue *structpb.Value `protobuf:"bytes,14,opt,name=value_value,json=valueValue,proto3,oneof"`
}

type MessageWithOneofWKTs_ListValueValue struct {
	ListValueValue *structpb.ListValue `protobuf:"bytes,15,opt,name=list_value_value,json=listValueValue,proto3,oneof"`
}

type MessageWithOneofWKTs_StructValue struct {
	StructValue *structpb.Struct `protobuf:"bytes,16,opt,name=struct_value,json=structValue,proto3,oneof"`
}

type MessageWithOneofWKTs_AnyValue struct {
	AnyValue *anypb.Any `protobuf:"bytes,17,opt,name=any_value,json=anyValue,proto3,oneof"`
}

func (*MessageWithOneofWKTs_DoubleValue) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_FloatValue) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_Int32Value) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_Int64Value) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_Uint32Value) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_Uint64Value) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_BoolValue) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_StringValue) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_BytesValue) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_EmptyValue) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_TimestampValue) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_DurationValue) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_FieldMaskValue) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_ValueValue) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_ListValueValue) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_StructValue) isMessageWithOneofWKTs_Value() {}

func (*MessageWithOneofWKTs_AnyValue) isMessageWithOneofWKTs_Value() {}

type MessageWithWKTMaps struct {
	state              protoimpl.MessageState             `protogen:"open.v1"`
	StringDoubleMap    map[string]*wrapperspb.DoubleValue `protobuf:"bytes,1,rep,name=string_double_map,json=stringDoubleMap,proto3" json:"string_double_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringFloatMap     map[string]*wrapperspb.FloatValue  `protobuf:"bytes,2,rep,name=string_float_map,json=stringFloatMap,proto3" json:"string_float_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringInt32Map     map[string]*wrapperspb.Int32Value  `protobuf:"bytes,3,rep,name=string_int32_map,json=stringInt32Map,proto3" json:"string_int32_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringInt64Map     map[string]*wrapperspb.Int64Value  `protobuf:"bytes,4,rep,name=string_int64_map,json=stringInt64Map,proto3" json:"string_int64_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringUint32Map    map[string]*wrapperspb.UInt32Value `protobuf:"bytes,5,rep,name=string_uint32_map,json=stringUint32Map,proto3" json:"string_uint32_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringUint64Map    map[string]*wrapperspb.UInt64Value `protobuf:"bytes,6,rep,name=string_uint64_map,json=stringUint64Map,proto3" json:"string_uint64_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringBoolMap      map[string]*wrapperspb.BoolValue   `protobuf:"bytes,7,rep,name=string_bool_map,json=stringBoolMap,proto3" json:"string_bool_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringStringMap    map[string]*wrapperspb.StringValue `protobuf:"bytes,8,rep,name=string_string_map,json=stringStringMap,proto3" json:"string_string_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringBytesMap     map[string]*wrapperspb.BytesValue  `protobuf:"bytes,9,rep,name=string_bytes_map,json=stringBytesMap,proto3" json:"string_bytes_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringEmptyMap     map[string]*emptypb.Empty          `protobuf:"bytes,10,rep,name=string_empty_map,json=stringEmptyMap,proto3" json:"string_empty_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringTimestampMap map[string]*timestamppb.Timestamp  `protobuf:"bytes,11,rep,name=string_timestamp_map,json=stringTimestampMap,proto3" json:"string_timestamp_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringDurationMap  map[string]*durationpb.Duration    `protobuf:"bytes,12,rep,name=string_duration_map,json=stringDurationMap,proto3" json:"string_duration_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringFieldMaskMap map[string]*fieldmaskpb.FieldMask  `protobuf:"bytes,13,rep,name=string_field_mask_map,json=stringFieldMaskMap,proto3" json:"string_field_mask_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringValueMap     map[string]*structpb.Value         `protobuf:"bytes,14,rep,name=string_value_map,json=stringValueMap,proto3" json:"string_value_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringListValueMap map[string]*structpb.ListValue     `protobuf:"bytes,15,rep,name=string_list_value_map,json=stringListValueMap,proto3" json:"string_list_value_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringStructMap    map[string]*structpb.Struct        `protobuf:"bytes,16,rep,name=string_struct_map,json=stringStructMap,proto3" json:"string_struct_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringAnyMap       map[string]*anypb.Any              `protobuf:"bytes,17,rep,name=string_any_map,json=stringAnyMap,proto3" json:"string_any_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MessageWithWKTMaps) Reset() {
	*x = MessageWithWKTMaps{}
	mi := &file_wkts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithWKTMaps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithWKTMaps) ProtoMessage() {}

func (x *MessageWithWKTMaps) ProtoReflect() protoreflect.Message {
	mi := &file_wkts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithWKTMaps.ProtoReflect.Descriptor instead.
func (*MessageWithWKTMaps) Descriptor() ([]byte, []int) {
	return file_wkts_proto_rawDescGZIP(), []int{2}
}

func (x *MessageWithWKTMaps) GetStringDoubleMap() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.StringDoubleMap
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringFloatMap() map[string]*wrapperspb.FloatValue {
	if x != nil {
		return x.StringFloatMap
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringInt32Map() map[string]*wrapperspb.Int32Value {
	if x != nil {
		return x.StringInt32Map
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringInt64Map() map[string]*wrapperspb.Int64Value {
	if x != nil {
		return x.StringInt64Map
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringUint32Map() map[string]*wrapperspb.UInt32Value {
	if x != nil {
		return x.StringUint32Map
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringUint64Map() map[string]*wrapperspb.UInt64Value {
	if x != nil {
		return x.StringUint64Map
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringBoolMap() map[string]*wrapperspb.BoolValue {
	if x != nil {
		return x.StringBoolMap
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringStringMap() map[string]*wrapperspb.StringValue {
	if x != nil {
		return x.StringStringMap
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringBytesMap() map[string]*wrapperspb.BytesValue {
	if x != nil {
		return x.StringBytesMap
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringEmptyMap() map[string]*emptypb.Empty {
	if x != nil {
		return x.StringEmptyMap
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringTimestampMap() map[string]*timestamppb.Timestamp {
	if x != nil {
		return x.StringTimestampMap
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringDurationMap() map[string]*durationpb.Duration {
	if x != nil {
		return x.StringDurationMap
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringFieldMaskMap() map[string]*fieldmaskpb.FieldMask {
	if x != nil {
		return x.StringFieldMaskMap
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringValueMap() map[string]*structpb.Value {
	if x != nil {
		return x.StringValueMap
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringListValueMap() map[string]*structpb.ListValue {
	if x != nil {
		return x.StringListValueMap
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringStructMap() map[string]*structpb.Struct {
	if x != nil {
		return x.StringStructMap
	}
	return nil
}

func (x *MessageWithWKTMaps) GetStringAnyMap() map[string]*anypb.Any {
	if x != nil {
		return x.StringAnyMap
	}
	return nil
}

var File_wkts_proto protoreflect.FileDescriptor

const file_wkts_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"wkts.proto\x12\x14thethings.flags.test\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a!thethings/flags/annotations.proto\"\x93\x11\n" +
	"\x0fMessageWithWKTs\x12?\n" +
	"\fdouble_value\x18\x01 \x01(\v2\x1c.google.protobuf.DoubleValueR\vdoubleValue\x12A\n" +
	"\rdouble_values\x18\x02 \x03(\v2\x1c.google.protobuf.DoubleValueR\fdoubleValues\x12<\n" +
	"\vfloat_value\x18\x03 \x01(\v2\x1b.google.protobuf.FloatValueR\n" +
	"floatValue\x12>\n" +
	"\ffloat_values\x18\x04 \x03(\v2\x1b.google.protobuf.FloatValueR\vfloatValues\x12<\n" +
	"\vint32_value\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"int32Value\x12>\n" +
	"\fint32_values\x18\x06 \x03(\v2\x1b.google.protobuf.Int32ValueR\vint32Values\x12<\n" +
	"\vint64_value\x18\a \x01(\v2\x1b.google.protobuf.Int64ValueR\n" +
	"int64Value\x12>\n" +
	"\fint64_values\x18\b \x03(\v2\x1b.google.protobuf.Int64ValueR\vint64Values\x12?\n" +
	"\fuint32_value\x18\t \x01(\v2\x1c.google.protobuf.UInt32ValueR\vuint32Value\x12A\n" +
	"\ruint32_values\x18\n" +
	" \x03(\v2\x1c.google.protobuf.UInt32ValueR\fuint32Values\x12?\n" +
	"\fuint64_value\x18\v \x01(\v2\x1c.google.protobuf.UInt64ValueR\vuint64Value\x12A\n" +
	"\ruint64_values\x18\f \x03(\v2\x1c.google.protobuf.UInt64ValueR\fuint64Values\x129\n" +
	"\n" +
	"bool_value\x18\r \x01(\v2\x1a.google.protobuf.BoolValueR\tboolValue\x12;\n" +
	"\vbool_values\x18\x0e \x03(\v2\x1a.google.protobuf.BoolValueR\n" +
	"boolValues\x12?\n" +
	"\fstring_value\x18\x0f \x01(\v2\x1c.google.protobuf.StringValueR\vstringValue\x12A\n" +
	"\rstring_values\x18\x10 \x03(\v2\x1c.google.protobuf.StringValueR\fstringValues\x12<\n" +
	"\vbytes_value\x18\x11 \x01(\v2\x1b.google.protobuf.BytesValueR\n" +
	"bytesValue\x12>\n" +
	"\fbytes_values\x18\x12 \x03(\v2\x1b.google.protobuf.BytesValueR\vbytesValues\x127\n" +
	"\vempty_value\x18\x13 \x01(\v2\x16.google.protobuf.EmptyR\n" +
	"emptyValue\x129\n" +
	"\fempty_values\x18\x14 \x03(\v2\x16.google.protobuf.EmptyR\vemptyValues\x12C\n" +
	"\x0ftimestamp_value\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampValue\x12E\n" +
	"\x10timestamp_values\x18\x16 \x03(\v2\x1a.google.protobuf.TimestampR\x0ftimestampValues\x12@\n" +
	"\x0eduration_value\x18\x17 \x01(\v2\x19.google.protobuf.DurationR\rdurationValue\x12B\n" +
	"\x0fduration_values\x18\x18 \x03(\v2\x19.google.protobuf.DurationR\x0edurationValues\x12D\n" +
	"\x10field_mask_value\x18\x19 \x01(\v2\x1a.google.protobuf.FieldMaskR\x0efieldMaskValue\x12F\n" +
	"\x11field_mask_values\x18\x1a \x03(\v2\x1a.google.protobuf.FieldMaskR\x0ffieldMaskValues\x127\n" +
	"\vvalue_value\x18\x1b \x01(\v2\x16.google.protobuf.ValueR\n" +
	"valueValue\x129\n" +
	"\fvalue_values\x18\x1c \x03(\v2\x16.google.protobuf.ValueR\vvalueValues\x12D\n" +
	"\x10list_value_value\x18\x1d \x01(\v2\x1a.google.protobuf.ListValueR\x0elistValueValue\x12F\n" +
	"\x11list_value_values\x18\x1e \x03(\v2\x1a.google.protobuf.ListValueR\x0flistValueValues\x12:\n" +
	"\fstruct_value\x18\x1f \x01(\v2\x17.google.protobuf.StructR\vstructValue\x12<\n" +
	"\rstruct_values\x18  \x03(\v2\x17.google.protobuf.StructR\fstructValues\x121\n" +
	"\tany_value\x18! \x01(\v2\x14.google.protobuf.AnyR\banyValue\x123\n" +
	"\n" +
	"any_values\x18\" \x03(\v2\x14.google.protobuf.AnyR\tanyValues:\b\xf2\xaa\x19\x04\b\x01\x10\x01\"\xf6\b\n" +
	"\x14MessageWithOneofWKTs\x12A\n" +
	"\fdouble_value\x18\x01 \x01(\v2\x1c.google.protobuf.DoubleValueH\x00R\vdoubleValue\x12>\n" +
	"\vfloat_value\x18\x02 \x01(\v2\x1b.google.protobuf.FloatValueH\x00R\n" +
	"floatValue\x12>\n" +
	"\vint32_value\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueH\x00R\n" +
	"int32Value\x12>\n" +
	"\vint64_value\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueH\x00R\n" +
	"int64Value\x12A\n" +
	"\fuint32_value\x18\x05 \x01(\v2\x1c.google.protobuf.UInt32ValueH\x00R\vuint32Value\x12A\n" +
	"\fuint64_value\x18\x06 \x01(\v2\x1c.google.protobuf.UInt64ValueH\x00R\vuint64Value\x12;\n" +
	"\n" +
	"bool_value\x18\a \x01(\v2\x1a.google.protobuf.BoolValueH\x00R\tboolValue\x12A\n" +
	"\fstring_value\x18\b \x01(\v2\x1c.google.protobuf.StringValueH\x00R\vstringValue\x12>\n" +
	"\vbytes_value\x18\t \x01(\v2\x1b.google.protobuf.BytesValueH\x00R\n" +
	"bytesValue\x129\n" +
	"\vempty_value\x18\n" +
	" \x01(\v2\x16.google.protobuf.EmptyH\x00R\n" +
	"emptyValue\x12E\n" +
	"\x0ftimestamp_value\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValue\x12B\n" +
	"\x0eduration_value\x18\f \x01(\v2\x19.google.protobuf.DurationH\x00R\rdurationValue\x12F\n" +
	"\x10field_mask_value\x18\r \x01(\v2\x1a.google.protobuf.FieldMaskH\x00R\x0efieldMaskValue\x129\n" +
	"\vvalue_value\x18\x0e \x01(\v2\x16.google.protobuf.ValueH\x00R\n" +
	"valueValue\x12F\n" +
	"\x10list_value_value\x18\x0f \x01(\v2\x1a.google.protobuf.ListValueH\x00R\x0elistValueValue\x12<\n" +
	"\fstruct_value\x18\x10 \x01(\v2\x17.google.protobuf.StructH\x00R\vstructValue\x123\n" +
	"\tany_value\x18\x11 \x01(\v2\x14.google.protobuf.AnyH\x00R\banyValue:\b\xf2\xaa\x19\x04\b\x01\x10\x01B\a\n" +
	"\x05value\"\x95\x1b\n" +
	"\x12MessageWithWKTMaps\x12i\n" +
	"\x11string_double_map\x18\x01 \x03(\v2=.thethings.flags.test.MessageWithWKTMaps.StringDoubleMapEntryR\x0fstringDoubleMap\x12f\n" +
	"\x10string_float_map\x18\x02 \x03(\v2<.thethings.flags.test.MessageWithWKTMaps.StringFloatMapEntryR\x0estringFloatMap\x12f\n" +
	"\x10string_int32_map\x18\x03 \x03(\v2<.thethings.flags.test.MessageWithWKTMaps.StringInt32MapEntryR\x0estringInt32Map\x12f\n" +
	"\x10string_int64_map\x18\x04 \x03(\v2<.thethings.flags.test.MessageWithWKTMaps.StringInt64MapEntryR\x0estringInt64Map\x12i\n" +
	"\x11string_uint32_map\x18\x05 \x03(\v2=.thethings.flags.test.MessageWithWKTMaps.StringUint32MapEntryR\x0fstringUint32Map\x12i\n" +
	"\x11string_uint64_map\x18\x06 \x03(\v2=.thethings.flags.test.MessageWithWKTMaps.StringUint64MapEntryR\x0fstringUint64Map\x12c\n" +
	"\x0fstring_bool_map\x18\a \x03(\v2;.thethings.flags.test.MessageWithWKTMaps.StringBoolMapEntryR\rstringBoolMap\x12i\n" +
	"\x11string_string_map\x18\b \x03(\v2=.thethings.flags.test.MessageWithWKTMaps.StringStringMapEntryR\x0fstringStringMap\x12f\n" +
	"\x10string_bytes_map\x18\t \x03(\v2<.thethings.flags.test.MessageWithWKTMaps.StringBytesMapEntryR\x0estringBytesMap\x12f\n" +
	"\x10string_empty_map\x18\n" +
	" \x03(\v2<.thethings.flags.test.MessageWithWKTMaps.StringEmptyMapEntryR\x0estringEmptyMap\x12r\n" +
	"\x14string_timestamp_map\x18\v \x03(\v2@.thethings.flags.test.MessageWithWKTMaps.StringTimestampMapEntryR\x12stringTimestampMap\x12o\n" +
	"\x13string_duration_map\x18\f \x03(\v2?.thethings.flags.test.MessageWithWKTMaps.StringDurationMapEntryR\x11stringDurationMap\x12s\n" +
	"\x15string_field_mask_map\x18\r \x03(\v2@.thethings.flags.test.MessageWithWKTMaps.StringFieldMaskMapEntryR\x12stringFieldMaskMap\x12f\n" +
	"\x10string_value_map\x18\x0e \x03(\v2<.thethings.flags.test.MessageWithWKTMaps.StringValueMapEntryR\x0estringValueMap\x12s\n" +
	"\x15string_list_value_map\x18\x0f \x03(\v2@.thethings.flags.test.MessageWithWKTMaps.StringListValueMapEntryR\x12stringListValueMap\x12i\n" +
	"\x11string_struct_map\x18\x10 \x03(\v2=.thethings.flags.test.MessageWithWKTMaps.StringStructMapEntryR\x0fstringStructMap\x12`\n" +
	"\x0estring_any_map\x18\x11 \x03(\v2:.thethings.flags.test.MessageWithWKTMaps.StringAnyMapEntryR\fstringAnyMap\x1a`\n" +
	"\x14StringDoubleMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1a^\n" +
	"\x13StringFloatMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.FloatValueR\x05value:\x028\x01\x1a^\n" +
	"\x13StringInt32MapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05value:\x028\x01\x1a^\n" +
	"\x13StringInt64MapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05value:\x028\x01\x1a`\n" +
	"\x14StringUint32MapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x05value:\x028\x01\x1a`\n" +
	"\x14StringUint64MapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x05value:\x028\x01\x1a\\\n" +
	"\x12StringBoolMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\x05value:\x028\x01\x1a`\n" +
	"\x14StringStringMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05value:\x028\x01\x1a^\n" +
	"\x13StringBytesMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.BytesValueR\x05value:\x028\x01\x1aY\n" +
	"\x13StringEmptyMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.EmptyR\x05value:\x028\x01\x1aa\n" +
	"\x17StringTimestampMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value:\x028\x01\x1a_\n" +
	"\x16StringDurationMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05value:\x028\x01\x1aa\n" +
	"\x17StringFieldMaskMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\x05value:\x028\x01\x1aY\n" +
	"\x13StringValueMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\x1aa\n" +
	"\x17StringListValueMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.ListValueR\x05value:\x028\x01\x1a[\n" +
	"\x14StringStructMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01\x1aU\n" +
	"\x11StringAnyMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01:\b\xf2\xaa\x19\x04\b\x01\x10\x01B9Z7github.com/TheThingsIndustries/protoc-gen-go-flags/testb\x06proto3"

var (
	file_wkts_proto_rawDescOnce sync.Once
	file_wkts_proto_rawDescData []byte
)

func file_wkts_proto_rawDescGZIP() []byte {
	file_wkts_proto_rawDescOnce.Do(func() {
		file_wkts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wkts_proto_rawDesc), len(file_wkts_proto_rawDesc)))
	})
	return file_wkts_proto_rawDescData
}

var file_wkts_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_wkts_proto_goTypes = []any{
	(*MessageWithWKTs)(nil),        // 0: thethings.flags.test.MessageWithWKTs
	(*MessageWithOneofWKTs)(nil),   // 1: thethings.flags.test.MessageWithOneofWKTs
	(*MessageWithWKTMaps)(nil),     // 2: thethings.flags.test.MessageWithWKTMaps
	nil,                            // 3: thethings.flags.test.MessageWithWKTMaps.StringDoubleMapEntry
	nil,                            // 4: thethings.flags.test.MessageWithWKTMaps.StringFloatMapEntry
	nil,                            // 5: thethings.flags.test.MessageWithWKTMaps.StringInt32MapEntry
	nil,                            // 6: thethings.flags.test.MessageWithWKTMaps.StringInt64MapEntry
	nil,                            // 7: thethings.flags.test.MessageWithWKTMaps.StringUint32MapEntry
	nil,                            // 8: thethings.flags.test.MessageWithWKTMaps.StringUint64MapEntry
	nil,                            // 9: thethings.flags.test.MessageWithWKTMaps.StringBoolMapEntry
	nil,                            // 10: thethings.flags.test.MessageWithWKTMaps.StringStringMapEntry
	nil,                            // 11: thethings.flags.test.MessageWithWKTMaps.StringBytesMapEntry
	nil,                            // 12: thethings.flags.test.MessageWithWKTMaps.StringEmptyMapEntry
	nil,                            // 13: thethings.flags.test.MessageWithWKTMaps.StringTimestampMapEntry
	nil,                            // 14: thethings.flags.test.MessageWithWKTMaps.StringDurationMapEntry
	nil,                            // 15: thethings.flags.test.MessageWithWKTMaps.StringFieldMaskMapEntry
	nil,                            // 16: thethings.flags.test.MessageWithWKTMaps.StringValueMapEntry
	nil,                            // 17: thethings.flags.test.MessageWithWKTMaps.StringListValueMapEntry
	nil,                            // 18: thethings.flags.test.MessageWithWKTMaps.StringStructMapEntry
	nil,                            // 19: thethings.flags.test.MessageWithWKTMaps.StringAnyMapEntry
	(*wrapperspb.DoubleValue)(nil), // 20: google.protobuf.DoubleValue
	(*wrapperspb.FloatValue)(nil),  // 21: google.protobuf.FloatValue
	(*wrapperspb.Int32Value)(nil),  // 22: google.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),  // 23: google.protobuf.Int64Value
	(*wrapperspb.UInt32Value)(nil), // 24: google.protobuf.UInt32Value
	(*wrapperspb.UInt64Value)(nil), // 25: google.protobuf.UInt64Value
	(*wrapperspb.BoolValue)(nil),   // 26: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil), // 27: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),  // 28: google.protobuf.BytesValue
	(*emptypb.Empty)(nil),          // 29: google.protobuf.Empty
	(*timestamppb.Timestamp)(nil),  // 30: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 31: google.protobuf.Duration
	(*fieldmaskpb.FieldMask)(nil),  // 32: google.protobuf.FieldMask
	(*structpb.Value)(nil),         // 33: google.protobuf.Value
	(*structpb.ListValue)(nil),     // 34: google.protobuf.ListValue
	(*structpb.Struct)(nil),        // 35: google.protobuf.Struct
	(*anypb.Any)(nil),              // 36: google.protobuf.Any
}
var file_wkts_proto_depIdxs = []int32{
	20, // 0: thethings.flags.test.MessageWithWKTs.double_value:type_name -> google.protobuf.DoubleValue
	20, // 1: thethings.flags.test.MessageWithWKTs.double_values:type_name -> google.protobuf.DoubleValue
	21, // 2: thethings.flags.test.MessageWithWKTs.float_value:type_name -> google.protobuf.FloatValue
	21, // 3: thethings.flags.test.MessageWithWKTs.float_values:type_name -> google.protobuf.FloatValue
	22, // 4: thethings.flags.test.MessageWithWKTs.int32_value:type_name -> google.protobuf.Int32Value
	22, // 5: thethings.flags.test.MessageWithWKTs.int32_values:type_name -> google.protobuf.Int32Value
	23, // 6: thethings.flags.test.MessageWithWKTs.int64_value:type_name -> google.protobuf.Int64Value
	23, // 7: thethings.flags.test.MessageWithWKTs.int64_values:type_name -> google.protobuf.Int64Value
	24, // 8: thethings.flags.test.MessageWithWKTs.uint32_value:type_name -> google.protobuf.UInt32Value
	24, // 9: thethings.flags.test.MessageWithWKTs.uint32_values:type_name -> google.protobuf.UInt32Value
	25, // 10: thethings.flags.test.MessageWithWKTs.uint64_value:type_name -> google.protobuf.UInt64Value
	25, // 11: thethings.flags.test.MessageWithWKTs.uint64_values:type_name -> google.protobuf.UInt64Value
	26, // 12: thethings.flags.test.MessageWithWKTs.bool_value:type_name -> google.protobuf.BoolValue
	26, // 13: thethings.flags.test.MessageWithWKTs.bool_values:type_name -> google.protobuf.BoolValue
	27, // 14: thethings.flags.test.MessageWithWKTs.string_value:type_name -> google.protobuf.StringValue
	27, // 15: thethings.flags.test.MessageWithWKTs.string_values:type_name -> google.protobuf.StringValue
	28, // 16: thethings.flags.test.MessageWithWKTs.bytes_value:type_name -> google.protobuf.BytesValue
	28, // 17: thethings.flags.test.MessageWithWKTs.bytes_values:type_name -> google.protobuf.BytesValue
	29, // 18: thethings.flags.test.MessageWithWKTs.empty_value:type_name -> google.protobuf.Empty
	29, // 19: thethings.flags.test.MessageWithWKTs.empty_values:type_name -> google.protobuf.Empty
	30, // 20: thethings.flags.test.MessageWithWKTs.timestamp_value:type_name -> google.protobuf.Timestamp
	30, // 21: thethings.flags.test.MessageWithWKTs.timestamp_values:type_name -> google.protobuf.Timestamp
	31, // 22: thethings.flags.test.MessageWithWKTs.duration_value:type_name -> google.protobuf.Duration
	31, // 23: thethings.flags.test.MessageWithWKTs.duration_values:type_name -> google.protobuf.Duration
	32, // 24: thethings.flags.test.MessageWithWKTs.field_mask_value:type_name -> google.protobuf.FieldMask
	32, // 25: thethings.flags.test.MessageWithWKTs.field_mask_values:type_name -> google.protobuf.FieldMask
	33, // 26: thethings.flags.test.MessageWithWKTs.value_value:type_name -> google.protobuf.Value
	33, // 27: thethings.flags.test.MessageWithWKTs.value_values:type_name -> google.protobuf.Value
	34, // 28: thethings.flags.test.MessageWithWKTs.list_value_value:type_name -> google.protobuf.ListValue
	34, // 29: thethings.flags.test.MessageWithWKTs.list_value_values:type_name -> google.protobuf.ListValue
	35, // 30: thethings.flags.test.MessageWithWKTs.struct_value:type_name -> google.protobuf.Struct
	35, // 31: thethings.flags.test.MessageWithWKTs.struct_values:type_name -> google.protobuf.Struct
	36, // 32: thethings.flags.test.MessageWithWKTs.any_value:type_name -> google.protobuf.Any
	36, // 33: thethings.flags.test.MessageWithWKTs.any_values:type_name -> google.protobuf.Any
	20, // 34: thethings.flags.test.MessageWithOneofWKTs.double_value:type_name -> google.protobuf.DoubleValue
	21, // 35: thethings.flags.test.MessageWithOneofWKTs.float_value:type_name -> google.protobuf.FloatValue
	22, // 36: thethings.flags.test.MessageWithOneofWKTs.int32_value:type_name -> google.protobuf.Int32Value
	23, // 37: thethings.flags.test.MessageWithOneofWKTs.int64_value:type_name -> google.protobuf.Int64Value
	24, // 38: thethings.flags.test.MessageWithOneofWKTs.uint32_value:type_name -> google.protobuf.UInt32Value
	25, // 39: thethings.flags.test.MessageWithOneofWKTs.uint64_value:type_name -> google.protobuf.UInt64Value
	26, // 40: thethings.flags.test.MessageWithOneofWKTs.bool_value:type_name -> google.protobuf.BoolValue
	27, // 41: thethings.flags.test.MessageWithOneofWKTs.string_value:type_name -> google.protobuf.StringValue
	28, // 42: thethings.flags.test.MessageWithOneofWKTs.bytes_value:type_name -> google.protobuf.BytesValue
	29, // 43: thethings.flags.test.MessageWithOneofWKTs.empty_value:type_name -> google.protobuf.Empty
	30, // 44: thethings.flags.test.MessageWithOneofWKTs.timestamp_value:type_name -> google.protobuf.Timestamp
	31, // 45: thethings.flags.test.MessageWithOneofWKTs.duration_value:type_name -> google.protobuf.Duration
	32, // 46: thethings.flags.test.MessageWithOneofWKTs.field_mask_value:type_name -> google.protobuf.FieldMask
	33, // 47: thethings.flags.test.MessageWithOneofWKTs.value_value:type_name -> google.protobuf.Value
	34, // 48: thethings.flags.test.MessageWithOneofWKTs.list_value_value:type_name -> google.protobuf.ListValue
	35, // 49: thethings.flags.test.MessageWithOneofWKTs.struct_value:type_name -> google.protobuf.Struct
	36, // 50: thethings.flags.test.MessageWithOneofWKTs.any_value:type_name -> google.protobuf.Any
	3,  // 51: thethings.flags.test.MessageWithWKTMaps.string_double_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringDoubleMapEntry
	4,  // 52: thethings.flags.test.MessageWithWKTMaps.string_float_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringFloatMapEntry
	5,  // 53: thethings.flags.test.MessageWithWKTMaps.string_int32_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringInt32MapEntry
	6,  // 54: thethings.flags.test.MessageWithWKTMaps.string_int64_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringInt64MapEntry
	7,  // 55: thethings.flags.test.MessageWithWKTMaps.string_uint32_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringUint32MapEntry
	8,  // 56: thethings.flags.test.MessageWithWKTMaps.string_uint64_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringUint64MapEntry
	9,  // 57: thethings.flags.test.MessageWithWKTMaps.string_bool_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringBoolMapEntry
	10, // 58: thethings.flags.test.MessageWithWKTMaps.string_string_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringStringMapEntry
	11, // 59: thethings.flags.test.MessageWithWKTMaps.string_bytes_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringBytesMapEntry
	12, // 60: thethings.flags.test.MessageWithWKTMaps.string_empty_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringEmptyMapEntry
	13, // 61: thethings.flags.test.MessageWithWKTMaps.string_timestamp_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringTimestampMapEntry
	14, // 62: thethings.flags.test.MessageWithWKTMaps.string_duration_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringDurationMapEntry
	15, // 63: thethings.flags.test.MessageWithWKTMaps.string_field_mask_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringFieldMaskMapEntry
	16, // 64: thethings.flags.test.MessageWithWKTMaps.string_value_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringValueMapEntry
	17, // 65: thethings.flags.test.MessageWithWKTMaps.string_list_value_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringListValueMapEntry
	18, // 66: thethings.flags.test.MessageWithWKTMaps.string_struct_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringStructMapEntry
	19, // 67: thethings.flags.test.MessageWithWKTMaps.string_any_map:type_name -> thethings.flags.test.MessageWithWKTMaps.StringAnyMapEntry
	20, // 68: thethings.flags.test.MessageWithWKTMaps.StringDoubleMapEntry.value:type_name -> google.protobuf.DoubleValue
	21, // 69: thethings.flags.test.MessageWithWKTMaps.StringFloatMapEntry.value:type_name -> google.protobuf.FloatValue
	22, // 70: thethings.flags.test.MessageWithWKTMaps.StringInt32MapEntry.value:type_name -> google.protobuf.Int32Value
	23, // 71: thethings.flags.test.MessageWithWKTMaps.StringInt64MapEntry.value:type_name -> google.protobuf.Int64Value
	24, // 72: thethings.flags.test.MessageWithWKTMaps.StringUint32MapEntry.value:type_name -> google.protobuf.UInt32Value
	25, // 73: thethings.flags.test.MessageWithWKTMaps.StringUint64MapEntry.value:type_name -> google.protobuf.UInt64Value
	26, // 74: thethings.flags.test.MessageWithWKTMaps.StringBoolMapEntry.value:type_name -> google.protobuf.BoolValue
	27, // 75: thethings.flags.test.MessageWithWKTMaps.StringStringMapEntry.value:type_name -> google.protobuf.StringValue
	28, // 76: thethings.flags.test.MessageWithWKTMaps.StringBytesMapEntry.value:type_name -> google.protobuf.BytesValue
	29, // 77: thethings.flags.test.MessageWithWKTMaps.StringEmptyMapEntry.value:type_name -> google.protobuf.Empty
	30, // 78: thethings.flags.test.MessageWithWKTMaps.StringTimestampMapEntry.value:type_name -> google.protobuf.Timestamp
	31, // 79: thethings.flags.test.MessageWithWKTMaps.StringDurationMapEntry.value:type_name -> google.protobuf.Duration
	32, // 80: thethings.flags.test.MessageWithWKTMaps.StringFieldMaskMapEntry.value:type_name -> google.protobuf.FieldMask
	33, // 81: thethings.flags.test.MessageWithWKTMaps.StringValueMapEntry.value:type_name -> google.protobuf.Value
	34, // 82: thethings.flags.test.MessageWithWKTMaps.StringListValueMapEntry.value:type_name -> google.protobuf.ListValue
	35, // 83: thethings.flags.test.MessageWithWKTMaps.StringStructMapEntry.value:type_name -> google.protobuf.Struct
	36, // 84: thethings.flags.test.MessageWithWKTMaps.StringAnyMapEntry.value:type_name -> google.protobuf.Any
	85, // [85:85] is the sub-list for method output_type
	85, // [85:85] is the sub-list for method input_type
	85, // [85:85] is the sub-list for extension type_name
	85, // [85:85] is the sub-list for extension extendee
	0,  // [0:85] is the sub-list for field type_name
}

func init() { file_wkts_proto_init() }
func file_wkts_proto_init() {
	if File_wkts_proto != nil {
		return
	}
	file_wkts_proto_msgTypes[1].OneofWrappers = []any{
		(*MessageWithOneofWKTs_DoubleValue)(nil),
		(*MessageWithOneofWKTs_FloatValue)(nil),
		(*MessageWithOneofWKTs_Int32Value)(nil),
		(*MessageWithOneofWKTs_Int64Value)(nil),
		(*MessageWithOneofWKTs_Uint32Value)(nil),
		(*MessageWithOneofWKTs_Uint64Value)(nil),
		(*MessageWithOneofWKTs_BoolValue)(nil),
		(*MessageWithOneofWKTs_StringValue)(nil),
		(*MessageWithOneofWKTs_BytesValue)(nil),
		(*MessageWithOneofWKTs_EmptyValue)(nil),
		(*MessageWithOneofWKTs_TimestampValue)(nil),
		(*MessageWithOneofWKTs_DurationValue)(nil),
		(*MessageWithOneofWKTs_FieldMaskValue)(nil),
		(*MessageWithOneofWKTs_ValueValue)(nil),
		(*MessageWithOneofWKTs_ListValueValue)(nil),
		(*MessageWithOneofWKTs_StructValue)(nil),
		(*MessageWithOneofWKTs_AnyValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wkts_proto_rawDesc), len(file_wkts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wkts_proto_goTypes,
		DependencyIndexes: file_wkts_proto_depIdxs,
		MessageInfos:      file_wkts_proto_msgTypes,
	}.Build()
	File_wkts_proto = out.File
	file_wkts_proto_goTypes = nil
	file_wkts_proto_depIdxs = nil
}
